# Generated by Django 4.1.2 on 2022-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ideal_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ideal_stocks_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('stock_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=30)),
                ('animal_testing', models.BooleanField()),
                ('nuclear_war', models.BooleanField()),
                ('coal_power', models.BooleanField()),
                ('rainforest_destruction', models.BooleanField()),
            ],
        ),
    ]
